name: Push and Deploy Serverless function
on: push

jobs:
  deploy-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v1
      with:
        token: ${{ secrets.TOKEN }}
        bucket: ${{ secrets.BUCKET }}
        function_id: 'd4e51lt3fsj5veejuahh'
        runtime: 'golang116'
        memory: '128'
        entrypoint: 'serverless.Handler'
        source: './goServerless'
        exclude: 'src/'
  deploy-node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v1
      with:
        token: ${{ secrets.TOKEN }}
        bucket: ${{ secrets.BUCKET }}
        function_id: 'd4e6q0a2bm7knun0pt0j'
        runtime: 'nodejs12'
        memory: '128'
        entrypoint: 'option2.handler'
        source: './nodeServerless'
        exclude: 'src/'
  deploy-bash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v1
      with:
        token: ${{ secrets.TOKEN }}
        bucket: ${{ secrets.BUCKET }}
        function_id: 'd4ei2u5osankn87ssgcd'
        runtime: 'bash'
        memory: '128'
        entrypoint: 'serverless.sh'
        source: './bashServerless'
        exclude: 'src/'
